import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  advancedConcept1Sidebar: [{type: 'autogenerated', dirName: 'advanced-concept-1'}],
  advancedConcept2Sidebar: [{type: 'autogenerated', dirName: 'advanced-concept-2'}],
  basicConcept1Sidebar: [{type: 'autogenerated', dirName: 'basic-concept-1'}],
  basicConcept2Sidebar: [{type: 'autogenerated', dirName: 'basic-concept-2'}],
  project1Sidebar: [{type: 'autogenerated', dirName: 'project-1'}],
  project2Sidebar: [{type: 'autogenerated', dirName: 'project-2'}],
  technology1Sidebar: [{type: 'autogenerated', dirName: 'technology-1'}],
  technology2Sidebar: [{type: 'autogenerated', dirName: 'technology-2'}],
};

export default sidebars;
